[workspace]
# Use `borsh` crate CHANGELOG as top-level one
changelog_update = false

[[package]]
name = "borsh"
changelog_update = true
changelog_path = "./CHANGELOG.md"
changelog_include = ["borsh-derive"] 

[[package]]
name = "fuzz-run"
publish = false

[[package]]
name = "benchmark"
publish = false
